site_name: Zauberwürfellöseroboter
site_url: https://scaui0.github.io
site_description: Erstellung eines Zauberwürfel-lösenden Roboters.
copyright: Copyright &copy; 2024-2025 Franz Weingartz
theme:
  language: de
  name: material
#  logo: assets/images/icon.svg
  icon:
    logo: material/cube
#  favicon: assets/images/icon.svg
#  favicon: material/cube
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
#    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.footer
    - content.tooltips
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - toc.follow
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

plugins:
  - search
#  - awesome-nav
#  - group:
##      enabled: !ENV [GITHUB, false]
#      enabled: true
#      plugins:
#        - social
#        - macros
#        - exporter:
#            enabled: !ENV [PDF, false]
##            enabled: true
#            logging:
#              level: debug
#            formats:
#              pdf:
#                concurrency: 32
#                stylesheets:
#                  - docs/assets/stylesheets/pdf.scss
#                covers:
#                  front: docs/assets/covers/front.html.j2
#                  back: docs/assets/covers/back.html.j2
#                browser:
#                  debug: false
#                aggregator:
#                  enabled: true
#                  output: documentation.pdf
#                  covers: book

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - md_in_html

  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#      options:
#        custom_icons:
#          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - docs/includes/glossary.md
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
#  - assets/javascripts/mkdocs-exporter.js
#  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.1/mermaid.min.js
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/stylesheets/extra.css
#  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  project_name: Zauberwürfellöseroboter

nav:
#  - Startseite: index.md
  - Tagebuch: diary.md
  - Fachbegriffe: technical_terms.md
  - Farberkennung: color_detection.md
  - Server:
      - server/index.md
      - Hilfsmitttel: server/utils.md
      - Kommunikation: server/communication.md
  - Löser:
      - solver/index.md
      - Koordinaten-Berechnung: solver/coordinates.md
      - IDA*: solver/ida_star.md
      - Korf: solver/korf.md
      - Thistlethwaite: solver/thistlethwaite.md
  - Der Roboter:
      robot/index.md
#  - Erklärungen: explanations.md
#  - Informationen: about.md
  - About:
      - about/index.md
      - about/about_documentation.md
  - Galerie: gallery.md